# Generated by Django 4.2 on 2026-05-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('verified', 'VERIFIED'), ('awaiting_payment', 'AWAITING_PAYMENT'), ('payment_received', 'PAYMENT_RECEIVED'), ('claimed', 'CLAIMED'), ('rejected', 'REJECTED'), ('disputed', 'DISPUTED')], default='pending', max_length=20)),
                ('security_answer', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('payment_received', models.BooleanField(default=False)),
                ('receipt_generated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('auto_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('id', 'ID'), ('bank_card', 'BANK_CARD'), ('keys', 'KEYS'), ('document', 'DOCUMENT'), ('gadget', 'GADGET'), ('other', 'OTHER')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(max_length=255)),
                ('found_date', models.DateTimeField()),
                ('original_image_url', models.URLField(blank=True)),
                ('blurred_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('active', 'ACTIVE'), ('claimed', 'CLAIMED'), ('blur_failed', 'BLUR_FAILED'), ('expired', 'EXPIRED')], default='processing', max_length=20)),
                ('security_question', models.TextField(blank=True)),
                ('security_answer', models.TextField(blank=True)),
                ('locator_name', models.CharField(blank=True, max_length=255)),
                ('locator_phone', models.CharField(blank=True, max_length=15)),
                ('is_fee_required', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(max_length=50)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='found_items.founditem')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='found_items.claim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransactionlog',
            index=models.Index(fields=['created_at'], name='found_items_created_60763d_idx'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='locator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founditem',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='found_items.founditem'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['status', 'category'], name='found_items_status_0649ea_idx'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['found_date'], name='found_items_found_d_0531cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('item', 'claimant')},
        ),
    ]
