# Generated by Django 4.2 on 2026-05-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='admission_number_on_item',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
