# Generated by Django 4.2 on 2026-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0003_alter_paymenttransaction_options_alter_tip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('ownership_verified', 'OWNERSHIP_VERIFIED'), ('evidence_submitted', 'EVIDENCE_SUBMITTED'), ('security_verified', 'SECURITY_VERIFIED'), ('payment_pending', 'PAYMENT_PENDING'), ('payment_received', 'PAYMENT_RECEIVED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('disputed', 'DISPUTED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('id', 'ID_CARD'), ('bank_card', 'BANK_CARD'), ('keys', 'KEYS'), ('gadget', 'GADGET'), ('document', 'DOCUMENT'), ('clothing', 'CLOTHING'), ('bag', 'BAG'), ('other', 'OTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('processing', 'PROCESSING'), ('active', 'ACTIVE'), ('pending_claim', 'PENDING_CLAIM'), ('claimed', 'CLAIMED'), ('handed_over', 'HANDED_OVER'), ('archived', 'ARCHIVED'), ('blur_failed', 'BLUR_FAILED'), ('disputed', 'DISPUTED')], default='processing', max_length=20),
        ),
    ]
