# Generated by Django 4.2 on 2026-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0004_alter_claim_status_alter_founditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='failed_security_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
