# Generated by Django 4.2 on 2026-06-05 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('push_announcement', models.BooleanField(default=True)),
                ('push_class', models.BooleanField(default=True)),
                ('push_found_item', models.BooleanField(default=True)),
                ('push_opportunity', models.BooleanField(default=True)),
                ('push_support', models.BooleanField(default=True)),
                ('push_governance', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_type',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('found_item', 'Found Item'), ('opportunity', 'Opportunity'), ('support', 'Support Ticket'), ('governance', 'Governance'), ('system', 'System')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('announcement_urgent', 'Urgent Announcement'), ('attendance_reminder', 'Attendance Reminder'), ('class_reminder', 'Class Reminder'), ('item_found', 'Item Found'), ('claim_update', 'Claim Update'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('tip_received', 'Tip Received'), ('role_assigned', 'Role Assigned'), ('role_expired', 'Role Expired'), ('role_expiring_soon', 'Role Expiring Soon'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('ticket_updated', 'Ticket Updated'), ('badge_earned', 'Badge Earned'), ('opportunity_expiring', 'Opportunity Expiring'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_deleted'], name='notificatio_user_id_3f57b1_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
