# Generated by Django 4.2 on 2026-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('announcement_urgent', 'Urgent Announcement'), ('attendance_reminder', 'Attendance Reminder'), ('class_reminder', 'Class Reminder'), ('class_cancelled', 'Class Cancelled'), ('class_rescheduled', 'Class Rescheduled'), ('assignment_graded', 'Assignment Graded'), ('item_found', 'Item Found'), ('claim_update', 'Claim Update'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('tip_received', 'Tip Received'), ('role_assigned', 'Role Assigned'), ('role_expired', 'Role Expired'), ('role_expiring_soon', 'Role Expiring Soon'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('ticket_updated', 'Ticket Updated'), ('badge_earned', 'Badge Earned'), ('opportunity_expiring', 'Opportunity Expiring'), ('new_message', 'New Message'), ('mention', 'Mention'), ('reaction', 'Reaction'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_type',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('found_item', 'Found Item'), ('opportunity', 'Opportunity'), ('support', 'Support Ticket'), ('governance', 'Governance'), ('chat', 'Chat'), ('system', 'System')], max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'is_deleted'], name='notificatio_user_id_52f944_idx'),
        ),
    ]
