# Generated by Django 5.2.15 on 2026-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreference_push_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('announcement_urgent', 'Urgent Announcement'), ('attendance_reminder', 'Attendance Reminder'), ('attendance_verified', 'Attendance Verified'), ('attendance_manual_review', 'Attendance Review Required'), ('attendance_rejected', 'Attendance Rejected'), ('class_reminder', 'Class Reminder'), ('class_cancelled', 'Class Cancelled'), ('class_rescheduled', 'Class Rescheduled'), ('assignment_graded', 'Assignment Graded'), ('item_found', 'Item Found'), ('claim_update', 'Claim Update'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('tip_received', 'Tip Received'), ('role_assigned', 'Role Assigned'), ('role_expired', 'Role Expired'), ('role_expiring_soon', 'Role Expiring Soon'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('ticket_updated', 'Ticket Updated'), ('badge_earned', 'Badge Earned'), ('opportunity_expiring', 'Opportunity Expiring'), ('new_message', 'New Message'), ('mention', 'Mention'), ('reaction', 'Reaction'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_type',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('attendance', 'Attendance'), ('found_item', 'Found Item'), ('opportunity', 'Opportunity'), ('support', 'Support Ticket'), ('governance', 'Governance'), ('chat', 'Chat'), ('system', 'System')], max_length=30, null=True),
        ),
    ]
