# Generated by Django 4.2 on 2026-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_created_by_blogcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
