# Generated by Django 4.2 on 2026-05-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blogpost_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='flags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Flag',
                'verbose_name_plural': 'Post Flags',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
