# Generated by Django 4.2 on 2026-05-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_key', models.CharField(help_text='S3 object key', max_length=500)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('record_count', models.IntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('archive_format', models.CharField(default='parquet', max_length=20)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum for integrity verification', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Archive',
                'verbose_name_plural': 'Audit Archives',
                'ordering': ['-date_range_start'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('total_announcements', models.IntegerField(default=0)),
                ('active_announcements', models.IntegerField(default=0)),
                ('total_found_items', models.IntegerField(default=0)),
                ('claimed_items', models.IntegerField(default=0)),
                ('total_opportunities', models.IntegerField(default=0)),
                ('active_opportunities', models.IntegerField(default=0)),
                ('total_claims', models.IntegerField(default=0)),
                ('resolved_claims', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('active_roles', models.IntegerField(default=0)),
                ('expiring_roles_7d', models.IntegerField(default=0)),
                ('total_login_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Platform Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=50)),
                ('scope_type', models.CharField(blank=True, max_length=50)),
                ('scope_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('modified', 'Modified')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Role Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REVOKED', 'Role Revoked'), ('ROLE_EXPIRED', 'Role Expired'), ('ANNOUNCEMENT_CREATED', 'Announcement Created'), ('ANNOUNCEMENT_DELETED', 'Announcement Deleted'), ('ANNOUNCEMENT_REPORTED', 'Announcement Reported'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('ITEM_REPORTED', 'Item Reported'), ('OPPORTUNITY_REPORTED', 'Opportunity Reported'), ('SESSION_REVOKED', 'Session Revoked'), ('SETTINGS_CHANGED', 'Settings Changed'), ('DATA_EXPORTED', 'Data Exported'), ('SYSTEM_ACTION', 'System Action')], db_index=True, max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_audit_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rolehistory',
            index=models.Index(fields=['user', 'created_at'], name='governance__user_id_0bcd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='rolehistory',
            index=models.Index(fields=['role', 'action'], name='governance__role_36fa57_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='governance__action_c1cdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='governance__target__bb73d0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='governance__perform_a31cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity'], name='governance__severit_935da9_idx'),
        ),
    ]
