# Generated by Django 4.2 on 2026-05-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Full venue name, e.g., 'Lecture Hall 3'", max_length=255)),
                ('institution', models.CharField(help_text="Institution name, e.g., 'Kenyatta University'", max_length=255)),
                ('building_code', models.CharField(blank=True, help_text="Short code, e.g., 'LH3'", max_length=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('full_address', models.TextField(blank=True, help_text='Complete address for geocoding fallback')),
                ('is_active', models.BooleanField(default=True)),
                ('venue_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('laboratory', 'Laboratory'), ('seminar_room', 'Seminar Room'), ('office', 'Office'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('sports', 'Sports Facility'), ('other', 'Other')], default='lecture_hall', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hit_count', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('nominatim', 'OpenStreetMap Nominatim'), ('manual', 'Manual Entry'), ('google', 'Google Maps')], default='nominatim', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Class Check-in'), ('manual', 'Manual Location Share'), ('background', 'Background Update')], default='check_in', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('student_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Calculated distance from venue', null=True)),
                ('within_radius', models.BooleanField(default=False)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('attendance_radius_meters', models.IntegerField(default=100)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('gps', 'GPS Only'), ('gps_wifi', 'GPS + WiFi'), ('manual', 'Manual Override')], default='gps', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_checkins', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_checkins', to='classes.timetableentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geocodingcache',
            index=models.Index(fields=['address'], name='geoservice__address_bcd79c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geocodingcache',
            unique_together={('address',)},
        ),
        migrations.AddIndex(
            model_name='campusvenue',
            index=models.Index(fields=['institution', 'is_active'], name='geoservice__institu_c192a7_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvenue',
            index=models.Index(fields=['latitude', 'longitude'], name='geoservice__latitud_f71931_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campusvenue',
            unique_together={('name', 'institution')},
        ),
        migrations.AddIndex(
            model_name='studentlocationhistory',
            index=models.Index(fields=['student', 'created_at'], name='geoservice__student_b5e8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlocationhistory',
            index=models.Index(fields=['event_type'], name='geoservice__event_t_902754_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcheckin',
            index=models.Index(fields=['student', 'created_at'], name='geoservice__student_24282f_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcheckin',
            index=models.Index(fields=['timetable_entry', 'created_at'], name='geoservice__timetab_fa3aff_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcheckin',
            index=models.Index(fields=['within_radius'], name='geoservice__within__50c124_idx'),
        ),
    ]
