# Generated by Django 4.2 on 2026-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservice', '0003_campusvenue_updated_by_alter_campusvenue_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional verification metadata'),
        ),
        migrations.AlterField(
            model_name='geocodingcache',
            name='address',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='geocodingcache',
            name='source',
            field=models.CharField(choices=[('nominatim', 'OpenStreetMap Nominatim'), ('manual', 'Manual Entry'), ('venue_db', 'CampusVenue Exact'), ('venue_db_fuzzy', 'CampusVenue Fuzzy'), ('google', 'Google Maps')], default='nominatim', max_length=30),
        ),
        migrations.AlterField(
            model_name='locationcheckin',
            name='verification_method',
            field=models.CharField(choices=[('gps', 'GPS Only'), ('gps_wifi', 'GPS + WiFi'), ('manual', 'Manual Override'), ('gps_fair_accuracy', 'GPS Fair Accuracy'), ('gps_poor_accuracy_pending', 'Poor Accuracy - Pending Review')], default='gps', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentlocationhistory',
            name='event_type',
            field=models.CharField(choices=[('check_in', 'Class Check-in'), ('manual', 'Manual Location Share'), ('background', 'Background Update'), ('watch', 'Continuous Watch')], default='check_in', max_length=30),
        ),
        migrations.AddIndex(
            model_name='geocodingcache',
            index=models.Index(fields=['source', 'hit_count'], name='geoservice__source_5b695d_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcheckin',
            index=models.Index(fields=['is_verified'], name='geoservice__is_veri_f987cc_idx'),
        ),
    ]
