# Generated by Django 4.2 on 2026-05-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, help_text='The type of action performed (e.g., ROLE_ASSIGNED, ROLE_EXPIRED)', max_length=50)),
                ('target_type', models.CharField(help_text='Type of object affected (e.g., StudentRole, User, Announcement)', max_length=50)),
                ('target_id', models.CharField(help_text='UUID or ID of the affected object', max_length=50)),
                ('before_state', models.JSONField(default=dict, help_text='Full state of the object BEFORE the action')),
                ('after_state', models.JSONField(default=dict, help_text='Full state of the object AFTER the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request that triggered this action', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent string of the client')),
                ('metadata', models.JSONField(default=dict, help_text='Additional contextual data (e.g., request headers, geo location)')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('class_rep', 'Class Representative'), ('student_leader', 'Student Leader'), ('faculty_rep', 'Faculty Representative')], help_text='The leadership role being assigned', max_length=20)),
                ('scope_type', models.CharField(choices=[('class', 'Class'), ('department', 'Department'), ('faculty', 'Faculty'), ('institution', 'Institution')], help_text='The scope of authority for this role', max_length=20)),
                ('scope_id', models.UUIDField(help_text='ID of the ClassGroup, Department, Faculty, or Institution this role governs')),
                ('scope_name', models.CharField(blank=True, help_text="Human-readable name of the scope (e.g., '3rd Year Microbiology')", max_length=255)),
                ('start_date', models.DateTimeField(help_text='When this role assignment becomes active')),
                ('end_date', models.DateTimeField(help_text='When this role assignment expires. Automatically deactivated by expire_roles task.')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False by expire_roles task when end_date passes, or manually by admin')),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for early revocation (if revoked before end_date)')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this role was manually revoked (if applicable)', null=True)),
            ],
            options={
                'verbose_name': 'Student Role Assignment',
                'verbose_name_plural': 'Student Role Assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.TextField(help_text='Encrypted refresh token')),
                ('device_info', models.JSONField(default=dict, help_text='Device information (type, OS, browser, IP)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when session is revoked or expires')),
                ('expires_at', models.DateTimeField(help_text='When this session naturally expires')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this session was manually revoked', null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this session was used')),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_system_user',
            field=models.BooleanField(default=False, help_text='If True, this user cannot be deleted through normal admin actions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Who revoked this session (admin or user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrole',
            name='assigned_by',
            field=models.ForeignKey(help_text='The admin/officer who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrole',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Who revoked this role (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrole',
            index=models.Index(fields=['user', 'is_active'], name='accounts_st_user_id_31414b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrole',
            index=models.Index(fields=['end_date', 'is_active'], name='accounts_st_end_dat_ed2558_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrole',
            index=models.Index(fields=['role', 'is_active'], name='accounts_st_role_de984f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrole',
            index=models.Index(fields=['scope_type', 'scope_id'], name='accounts_st_scope_t_d3ad96_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by'], name='accounts_au_perform_ee947f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_user'], name='accounts_au_target__c034cb_idx'),
        ),
    ]
