# Generated by Django 4.2 on 2026-05-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_studentrole_usersession_user_is_system_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
