# Generated by Django 4.2 on 2026-05-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_data',
            field=models.TextField(blank=True, help_text='Base64-encoded face image for cloud verification'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('login_bronze', 'LOGIN_BRONZE'), ('login_silver', 'LOGIN_SILVER'), ('login_gold', 'LOGIN_GOLD'), ('high_engager', 'HIGH_ENGAGER'), ('early_adopter', 'EARLY_ADOPTER'), ('top_contributor', 'TOP_CONTRIBUTOR'), ('perfect_attendance', 'PERFECT_ATTENDANCE'), ('community_helper', 'COMMUNITY_HELPER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('faculty_officer', 'FACULTY_OFFICER'), ('student_leader', 'STUDENT_LEADER'), ('faculty_rep', 'FACULTY_REP'), ('class_rep', 'CLASS_REP'), ('student', 'STUDENT')], default='student', max_length=20),
        ),
    ]
