# Generated by Django 4.2 on 2026-05-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_face_data_alter_badge_badge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrole',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_system_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
