# Generated by Django 5.2.15 on 2026-06-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, help_text='Color for the avatar placeholder (e.g., #6C63FF)', max_length=20),
        ),
    ]
