# Generated by Django 4.2 on 2026-05-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target', models.CharField(choices=[('entire_institution', 'ENTIRE_INSTITUTION'), ('specific_classes', 'SPECIFIC_CLASSES')], default='entire_institution', max_length=30)),
                ('is_urgent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('target_classes', models.ManyToManyField(blank=True, related_name='announcements', to='classes.classgroup')),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target', models.CharField(choices=[('class_rep', 'Class Representative'), ('student_leaders', 'Student Leaders'), ('both', 'Both')], default='class_rep', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('read', 'Read'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response_note', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='announcements.announcement')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reported_by', 'announcement')},
            },
        ),
        migrations.AddIndex(
            model_name='announcementrequest',
            index=models.Index(fields=['status'], name='announcemen_status_c944f8_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementrequest',
            index=models.Index(fields=['requester'], name='announcemen_request_8a928c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expires_at'], name='announcemen_expires_854584_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['posted_by', 'is_active'], name='announcemen_posted__7b76eb_idx'),
        ),
    ]
