# Generated by Django 4.2 on 2026-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'expires_at'], name='announcemen_is_acti_14a85b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_resolved', 'created_at'], name='announcemen_is_reso_ed1b4e_idx'),
        ),
    ]
