# Generated by Django 4.2 on 2026-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_announcemen_is_acti_14a85b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('entire_institution', 'ENTIRE_INSTITUTION'), ('specific_class', 'SPECIFIC_CLASS'), ('department', 'DEPARTMENT'), ('faculty', 'FACULTY'), ('student_leaders', 'STUDENT_LEADERS'), ('class_reps', 'CLASS_REPS')], default='entire_institution', max_length=30),
        ),
    ]
