# Generated by Django 4.2 on 2026-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrequest',
            name='target',
            field=models.CharField(choices=[('class_rep', 'Class Representative'), ('student_leaders', 'Student Leaders'), ('both', 'Both'), ('admin', 'Admin')], default='class_rep', max_length=30),
        ),
    ]
