import { useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { FiShield, FiCheckCircle, FiArrowLeft } from 'react-icons/fi';
import SkeletonLoader from '../components/shared/SkeletonLoader';

export default function TwoFactorSetupPage() {
    const { user, loading } = useAuth();
    const [enabled, setEnabled] = useState(user?.two_factor_enabled || false);
    const [toggling, setToggling] = useState(false);

    const handleToggle = async () => {
        setToggling(true);
        try {
            // Simulate API call – replace with your actual endpoint
            await new Promise((resolve) => setTimeout(resolve, 1000));
            // Suppose we call: await apiClient.post('/accounts/2fa/toggle/');
            const newStatus = !enabled;
            setEnabled(newStatus);
            toast.success(newStatus ? '2FA enabled' : '2FA disabled');
        } catch (err) {
            toast.error('Failed to update 2FA status');
        } finally {
            setToggling(false);
        }
    };

    if (loading) return <SkeletonLoader type="page" />;

    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 py-8 px-4">
            <div className="max-w-3xl mx-auto">
                <Link to="/profile" className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700 dark:text-gray-400 mb-6">
                    <FiArrowLeft className="w-4 h-4" /> Back to Profile
                </Link>

                <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-100 dark:border-gray-700 p-6 md:p-8">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="w-12 h-12 bg-indigo-100 dark:bg-indigo-900/30 rounded-xl flex items-center justify-center">
                            <FiShield className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
                        </div>
                        <h1 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">
                            Two-Factor Authentication
                        </h1>
                    </div>

                    <div className="bg-gray-50 dark:bg-gray-700/50 rounded-xl p-6 mb-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                                    Status: {enabled ? 'Enabled' : 'Disabled'}
                                </h3>
                                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                                    {enabled
                                        ? 'Your account is protected with an extra security layer.'
                                        : 'Add an extra layer of security to your account.'}
                                </p>
                            </div>
                            <button
                                onClick={handleToggle}
                                disabled={toggling}
                                className={`px-6 py-3 rounded-xl text-sm font-semibold text-white transition-colors shadow-md ${enabled
                                        ? 'bg-red-500 hover:bg-red-600'
                                        : 'bg-indigo-500 hover:bg-indigo-600'
                                    } disabled:opacity-50`}
                            >
                                {toggling ? 'Updating...' : enabled ? 'Disable' : 'Enable'}
                            </button>
                        </div>
                    </div>

                    <div className="border-t border-gray-100 dark:border-gray-700 pt-6">
                        <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">How it works</h2>
                        <ol className="list-decimal list-inside space-y-2 text-sm text-gray-600 dark:text-gray-400">
                            <li>Enable 2FA from the button above.</li>
                            <li>Scan the QR code with your authenticator app (Google Authenticator, Authy, etc.).</li>
                            <li>Enter the six‑digit code generated by the app when logging in.</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    );
}