# Generated by Django 5.2.15 on 2026-08-02 21:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('content', config='english'), name='chat_message_content_gin_idx'),
        ),
    ]
