# Generated by Django 4.2 on 2026-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='unread_count_receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='unread_count_sender',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
