# Generated by Django 4.2 on 2026-06-12 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_blockeduser_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
            },
        ),
        migrations.CreateModel(
            name='PinnedConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='chat.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Conversation',
                'verbose_name_plural': 'Pinned Conversations',
            },
        ),
        migrations.CreateModel(
            name='MutedConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('muted_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to='chat.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Muted Conversation',
                'verbose_name_plural': 'Muted Conversations',
            },
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reporter', 'reported_user'], name='chat_userre_reporte_db7650_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status'], name='chat_userre_status_a29211_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reason'], name='chat_userre_reason_376308_idx'),
        ),
        migrations.AddIndex(
            model_name='pinnedconversation',
            index=models.Index(fields=['user', 'conversation'], name='chat_pinned_user_id_9a064a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinnedconversation',
            unique_together={('user', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='mutedconversation',
            index=models.Index(fields=['user', 'conversation'], name='chat_mutedc_user_id_2fb617_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mutedconversation',
            unique_together={('user', 'conversation')},
        ),
    ]
