# Generated by Django 4.2 on 2026-06-12 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_conversation_deleted_by_message_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocked', 'blocker'], name='chat_blocke_blocked_3904f1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_deleted', 'created_at'], name='chat_messag_convers_ecc067_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['edited_at'], name='chat_messag_edited__39feea_idx'),
        ),
        migrations.AddIndex(
            model_name='mutedconversation',
            index=models.Index(fields=['conversation', 'user'], name='chat_mutedc_convers_bc537d_idx'),
        ),
        migrations.AddIndex(
            model_name='pinnedconversation',
            index=models.Index(fields=['user', '-pinned_at'], name='chat_pinned_user_id_586aae_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['created_at'], name='chat_userre_created_3357e7_idx'),
        ),
    ]
