# Generated by Django 4.2 on 2026-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_created_by_supportticket_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('in_progress', 'IN_PROGRESS'), ('awaiting_user', 'AWAITING_USER'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED'), ('reopened', 'REOPENED')], default='open', max_length=20),
        ),
    ]
